PALETTES = {
    "workflow": {
        "bg_top": "#f3fbfa",
        "bg_bottom": "#e7f0fb",
        "frame": "#ffffff",
        "stroke": "#d7e3eb",
        "ink": "#122738",
        "muted": "#5b6f82",
        "accent": "#0f8b8d",
        "accent_soft": "#d8f3f1",
        "secondary": "#375f95",
        "secondary_soft": "#dfe9fb",
        "warm": "#f5d8ab",
        "warm_soft": "#fff1d9",
        "good": "#2e8b57",
        "good_soft": "#ddf4e7",
        "shadow": "#d9e5ec",
    },
    "hub": {
        "bg_top": "#f6fafb",
        "bg_bottom": "#edf3f8",
        "frame": "#ffffff",
        "stroke": "#d7e3eb",
        "ink": "#13283a",
        "muted": "#617587",
        "accent": "#0f8b8d",
        "accent_soft": "#d8f3f1",
        "secondary": "#294b78",
        "secondary_soft": "#dfe7f6",
        "warm": "#ad7a38",
        "warm_soft": "#f9ecd8",
        "good": "#357d5c",
        "good_soft": "#ddf0e5",
        "shadow": "#d8e1e8",
    },
    "blueprint": {
        "bg_top": "#f3f7fd",
        "bg_bottom": "#edf7fb",
        "frame": "#ffffff",
        "stroke": "#d8e2eb",
        "ink": "#162a40",
        "muted": "#64778a",
        "accent": "#29548d",
        "accent_soft": "#dde7f7",
        "secondary": "#0f8b8d",
        "secondary_soft": "#d8f2f1",
        "warm": "#b07b33",
        "warm_soft": "#faecd5",
        "good": "#40755d",
        "good_soft": "#dfefe4",
        "shadow": "#d8e2eb",
    },
    "comparison": {
        "bg_top": "#fbf8f2",
        "bg_bottom": "#f3f7fb",
        "frame": "#ffffff",
        "stroke": "#dedfdd",
        "ink": "#1c2d3f",
        "muted": "#69798a",
        "accent": "#9a6d34",
        "accent_soft": "#f9ecd8",
        "secondary": "#2f5f95",
        "secondary_soft": "#dfe8f8",
        "warm": "#b87e2d",
        "warm_soft": "#fff0dc",
        "good": "#2f7a57",
        "good_soft": "#e1f1e8",
        "shadow": "#dddedd",
    },
}


def get_palette(name: str) -> dict:
    return PALETTES.get(name, PALETTES["workflow"])
